//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sewa
    {
        public int ID_Sewa { get; set; }
        public Nullable<int> ID_User { get; set; }
        public string ID_Buku { get; set; }
        public Nullable<int> HargaSewa { get; set; }
        public Nullable<System.DateTime> tglMulai { get; set; }
        public Nullable<System.DateTime> tglSelesai { get; set; }
        public Nullable<int> numberOfDay { get; set; }
        public Nullable<int> sewaAmount { get; set; }
    
        public virtual Buku Buku { get; set; }
        public virtual Register_User Register_User { get; set; }
    }
}
